spring:
  datasource:
    # H2 데이터베이스 설정
    h2:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
    redis:
      lettuce:
        pool:
          max-active: 10 # 최대 활성(사용 중) 커넥션 수, 동시에 열 수 있는 최대 커넥션 수를 지정합니다.
          max-idle: 10 # 커넥션 풀에 유지할 수 있는 최대 유휴(사용되지 않는) 커넥션 수, 필요 이상으로 커넥션이 생성되지 않도록 합니다.
          min-idle: 2 # 커넥션 풀에 유지할 최소 유휴 커넥션 수, 항상 일정 수준의 유휴 커넥션이 유지되도록 합니다.
      port: 6379 # Redis 서버의 포트, 기본값은 Redis의 기본 포트인 6379입니다.
      host: 127.0.0.1 # Redis 서버의 호스트 주소, 여기서는 로컬호스트를 가리킵니다.
      password: 1q2w3e4r # Redis 서버에 접속하기 위한 비밀번호, 보안을 위해 설정합니다.
